name: Deploy storybook

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Validate SSH test key
        run: cat ~/.ssh/id_rsa

      - name: Add nutanix.com to known hosts
        run: ssh-keyscan -H 3.81.226.191 >> ~/.ssh/known_hosts

      - name: Connect to SSH
        run: ssh ec2-user3.81.226.191 "ls -al"
